# Generated by Django 3.2.7 on 2021-09-19 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Temp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humidity', models.IntegerField()),
                ('bubble_point', models.IntegerField()),
                ('humid_volume', models.IntegerField()),
                ('density', models.IntegerField()),
            ],
        ),
    ]
